shuffle = true
repeat = "playlist"
[theme]
background = "#18181800"
primary = "#F1F1F1"
secondary = "#DCDCDC"
title = "#D5B0CE"
playing = "#94C2CD"
playing_selected = "#1ED760"
playing_bg = "#181818"
highlight = "#FFFFFF"
highlight_bg = "#B69EB2"
error = "#FFE4E4"
error_bg = "#B700C2"
statusbar = "#000000"
statusbar_progress = "#B69EB2"
statusbar_bg = "#94C2CD"
cmdline = "#FFFFFF"
cmdline_bg = "#444444"
